[package]
name = "plonky2-wraps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonky2 = "1.0.2"
anyhow = "1.0.56"
rand = "0.8.5"
rand_chacha = "0.3.1"
num = "0.4.0"