[package]
name = "experimental-frontends"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ark-ff = { workspace = true, features = ["asm"] }
ark-std = { workspace = true }
ark-relations = { workspace = true }
ark-r1cs-std = { workspace = true }
ark-serialize = { workspace = true }
ark-circom = { workspace = true }
num-bigint = { workspace = true }
noname = { workspace = true }
acvm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wasmer = { workspace = true }

folding-schemes = { workspace = true }

[dev-dependencies]
ark-bn254 = { workspace = true, features = ["r1cs"] }

[features]
default = ["parallel"]
parallel = [
    "folding-schemes/parallel",
]
